export const SAMPLE_DATA = {
  empresa: {
    nome: "JMFC Group",
    logo: "",
  },
  clientName: "JULIANO CAMPOS PEREIRA",
  clientCpf: "40340658851",
  consultationDate: "30/01/2026, 16:57:53",
  score: {
    pontuacao: 596,
    faixa: "REGULAR",
  },
  hasScore: true,
  scorePointer: {
    x: 120.19882754723837,
    y: 25.06921095722828,
  },
  scoreBandRange: "401 a 600",
  scoreBandLabel: "Regular",
  scoreBandSlug: "regular",
  scoreBandColor: "#ca8a04",
  scoreProbabilityPayment: "59.60",
  scoreProbabilityDefault: "40.40",
  scoreMetricDescription: "Quanto maior, melhor a predisposição ao crédito.",
  scoreFaixaDescription: "Risco moderado. Valide renda e estabilidade.",
  scoreProbPaymentDescription: "Estimativa de adimplência nos próximos 6 meses.",
  scoreProbDefaultDescription: "Estimativa de inadimplência — use como apoio à decisão.",
  scoreHeadline: "Como o mercado enxerga seu CPF hoje (e o que está travando seu crédito)",
  scoreSubtitulo: "Seu Score é uma estimativa de chance de pagar em dia nos próximos 6 meses. Quanto maior a pontuação, maior tende a ser a facilidade para conseguir crédito e melhores condições.",
  scoreFraseInterpretacao: "Hoje seu Score está em Regular (401 a 600) — isso geralmente indica que o mercado enxerga risco moderado. O objetivo aqui é identificar o que mais pesa na sua pontuação e montar o caminho mais rápido para destravar aprovações.",
  scoreInfluenciaTitulo: "O que mais influencia sua pontuação",
  scoreInfluenciaTexto: "O Serasa Score é calculado por pilares. Os que mais pesam são hábitos de pagamento e experiência/relacionamento com o mercado — e dívidas negativadas também têm impacto alto, considerando inclusive o tempo desde a quitação.",
  scoreInfluenciaLista: [
    "Pagamentos em dia (cartão, parcelas e contas) têm peso alto na pontuação.",
    "Dívidas negativadas costumam derrubar o Score e demoram a perder impacto sem regularização.",
    "Muitas consultas/simulações de crédito em pouco tempo podem pesar negativamente (busca por crédito).",
  ],
  scoreDiagnosticoTitulo: "Nós te ajudamos com tudo isso!",
  scoreDiagnosticoTexto: "O que trava crédito quase sempre é simples: pendência/negativação + histórico recente. A boa notícia é que, com estratégia, dá pra acelerar sua reabilitação e voltar a ser aprovado com mais facilidade.",
  protocol: "REQ-03073801",
  logoDataUrl: "",
  
  // CPC / Restrições
  scpc: [
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "16/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tipo": "-",
      "Tp Devedor": "-",
      "Vr Dívida": 116.66,
      "Contrato": "00000000000018330",
      "Origem": "SCPC SAO PAULO - SP",
      "Instituição": "SCPC SAO PAULO - SP",
      "Nome": "BANCO DO BRASIL S/A",
      "Avalista": "-",
      "Cidade": "SCPC SAO PAULO",
      "UF": "SP",
    },
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "16/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tipo": "-",
      "Tp Devedor": "-",
      "Vr Dívida": 284.52,
      "Contrato": "0006505699953889900",
      "Origem": "SCPC SAO PAULO - SP",
      "Instituição": "SCPC SAO PAULO - SP",
      "Nome": "BANCO PAN S/A",
      "Avalista": "-",
      "Cidade": "SCPC SAO PAULO",
      "UF": "SP",
    },
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "16/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tipo": "-",
      "Tp Devedor": "-",
      "Vr Dívida": 260.7,
      "Contrato": "CC-994280681",
      "Origem": "SCPC SAO PAULO - SP",
      "Instituição": "SCPC SAO PAULO - SP",
      "Nome": "MERCADO PAGO INST DE PAGAMENTO LTDA",
      "Avalista": "-",
      "Cidade": "SCPC SAO PAULO",
      "UF": "SP",
    },
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "16/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tipo": "-",
      "Tp Devedor": "-",
      "Vr Dívida": 4033.15,
      "Contrato": "00000000120714137",
      "Origem": "SCPC SAO PAULO - SP",
      "Instituição": "SCPC SAO PAULO - SP",
      "Nome": "BANCO DO BRASIL S/A",
      "Avalista": "-",
      "Cidade": "SCPC SAO PAULO",
      "UF": "SP",
    },
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "16/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tipo": "-",
      "Tp Devedor": "-",
      "Vr Dívida": 1561.33,
      "Contrato": "0000000147759188",
      "Origem": "SCPC SAO PAULO - SP",
      "Instituição": "SCPC SAO PAULO - SP",
      "Nome": "CREDSYSTEM INSTIT DE PAGAMENTO LTDA",
      "Avalista": "-",
      "Cidade": "SCPC SAO PAULO",
      "UF": "SP",
    },
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "16/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tipo": "-",
      "Tp Devedor": "-",
      "Vr Dívida": 457.51,
      "Contrato": "CC-941614956",
      "Origem": "SCPC SAO PAULO - SP",
      "Instituição": "SCPC SAO PAULO - SP",
      "Nome": "MERCADO PAGO INST DE PAGAMENTO LTDA",
      "Avalista": "-",
      "Cidade": "SCPC SAO PAULO",
      "UF": "SP",
    },
  ],
  
  protesto: [],
  refinPefin: [],
  
  serasaPremium: [
    {
      "Data Inclusão": "19/12/2025",
      "Data Vencimento": "09/11/2025",
      "Tp Devedor": "-",
      "Contrato": "FAT37521061",
      "Origem": "- MOGI GUACU/SP",
      "Vr Dívida": 942.07,
    },
    {
      "Data Inclusão": "15/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tp Devedor": "-",
      "Contrato": "00000000000000018330",
      "Origem": "- BRASILIA/DF",
      "Vr Dívida": 116.66,
    },
    {
      "Data Inclusão": "10/08/2025",
      "Data Vencimento": "02/07/2025",
      "Tp Devedor": "-",
      "Contrato": "6505699953889900",
      "Origem": "- SAO PAULO/SP",
      "Vr Dívida": 302.7,
    },
    {
      "Data Inclusão": "12/07/2025",
      "Data Vencimento": "20/04/2025",
      "Tp Devedor": "-",
      "Contrato": "F104071978",
      "Origem": "- CURITIBA/PR",
      "Vr Dívida": 825.24,
    },
    {
      "Data Inclusão": "14/05/2025",
      "Data Vencimento": "01/04/2025",
      "Tp Devedor": "-",
      "Contrato": "00000000000120714137",
      "Origem": "- BRASILIA/DF",
      "Vr Dívida": 4033.15,
    },
    {
      "Data Inclusão": "06/04/2025",
      "Data Vencimento": "21/02/2025",
      "Tp Devedor": "-",
      "Contrato": "12205000138708",
      "Origem": "- SAO PAULO/SP",
      "Vr Dívida": 84702.00,
    },
    {
      "Data Inclusão": "01/04/2025",
      "Data Vencimento": "20/02/2025",
      "Tp Devedor": "-",
      "Contrato": "147759188",
      "Origem": "- BARUERI/SP",
      "Vr Dívida": 1135.54,
    },
  ],
  
  spc: [
    {
      "Dt Ocorr": "09/11/2025",
      "Data Inclusão": "19/12/2025",
      "Data Vencimento": "09/11/2025",
      "Tp Devedor": "-",
      "Contrato": "FAT37521061",
      "Origem": "CDL - SAO PAULO / SP - MOGI GUACU/SP",
      "Vr Dívida": 942.07,
    },
    {
      "Dt Ocorr": "01/09/2025",
      "Data Inclusão": "15/10/2025",
      "Data Vencimento": "01/09/2025",
      "Tp Devedor": "-",
      "Contrato": "00000000000000018330",
      "Origem": "SAO PAULO / SP - BRASILIA/DF",
      "Vr Dívida": 116.66,
    },
    {
      "Dt Ocorr": "02/07/2025",
      "Data Inclusão": "10/08/2025",
      "Data Vencimento": "02/07/2025",
      "Tp Devedor": "-",
      "Contrato": "6505699953889900",
      "Origem": "SAO PAULO / SP - SAO PAULO/SP",
      "Vr Dívida": 302.7,
    },
    {
      "Dt Ocorr": "20/04/2025",
      "Data Inclusão": "12/07/2025",
      "Data Vencimento": "20/04/2025",
      "Tp Devedor": "-",
      "Contrato": "F104071978",
      "Origem": "SAO PAULO / SP - CURITIBA/PR",
      "Vr Dívida": 825.24,
    },
    {
      "Dt Ocorr": "01/04/2025",
      "Data Inclusão": "14/05/2025",
      "Data Vencimento": "01/04/2025",
      "Tp Devedor": "-",
      "Contrato": "00000000000120714137",
      "Origem": "SAO PAULO / SP - BRASILIA/DF",
      "Vr Dívida": 4033.15,
    },
    {
      "Dt Ocorr": "21/02/2025",
      "Data Inclusão": "06/04/2025",
      "Data Vencimento": "21/02/2025",
      "Tp Devedor": "-",
      "Contrato": "12205000138708",
      "Origem": "SAO PAULO / SP - SAO PAULO/SP",
      "Vr Dívida": 84702.00,
    },
    {
      "Dt Ocorr": "20/02/2025",
      "Data Inclusão": "01/04/2025",
      "Data Vencimento": "20/02/2025",
      "Tp Devedor": "-",
      "Contrato": "147759188",
      "Origem": "SAO PAULO / SP - BARUERI/SP",
      "Vr Dívida": 1135.54,
    },
  ],
  
  resumo: [],
  
  Bacen: {
    restricaoBacen: "20347,00",
    valorVencido: "20347,00",
    quantidadeInstituicoes: "5",
    quantidadeOperacoes: "9",
    dataBaseConsultada: "12/2025",
    dataInicioRelacionamento: "29/07/2019",
    consolidado: {
      PREJUIZO: {
        VALOR: "0,00",
        OPERACOES: [],
        PERCENTUAL: "0,00",
      },
      LIMITE_CREDITO: {
        VALOR: "2420,00",
        OPERACOES: [
          {
            VALOR: "2420",
            DESCRICAO: "LIMITE DE CREDITO COM VENCIMENTO ACIMA DE 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "3,62",
          },
        ],
        PERCENTUAL: "3,62",
      },
      CREDITO_AVENCER: {
        VALOR: "44139,00",
        OPERACOES: [
          {
            VALOR: "2769,00",
            DESCRICAO: "CREDITOS A VENCER ATE 30 DIAS",
            QTD_MESES: "1",
            PERCENTUAL: "4,14",
          },
          {
            VALOR: "2136,00",
            DESCRICAO: "CREDITOS A VENCER DE 31 A 60 DIAS",
            QTD_MESES: "2",
            PERCENTUAL: "3,19",
          },
          {
            VALOR: "1219",
            DESCRICAO: "CREDITOS A VENCER DE 61 A 90 DIAS",
            QTD_MESES: "3",
            PERCENTUAL: "1,82",
          },
          {
            VALOR: "4668,00",
            DESCRICAO: "CREDITOS A VENCER DE 91 A 180 DIAS",
            QTD_MESES: "6",
            PERCENTUAL: "6,98",
          },
          {
            VALOR: "8187,00",
            DESCRICAO: "CREDITOS A VENCER DE 181 A 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "12,24",
          },
          {
            VALOR: "11005,00",
            DESCRICAO: "CREDITOS A VENCER DE 361 A 720 DIAS",
            QTD_MESES: "24",
            PERCENTUAL: "16,45",
          },
          {
            VALOR: "7848",
            DESCRICAO: "CREDITOS A VENCER DE 721 A 1080 DIAS",
            QTD_MESES: "36",
            PERCENTUAL: "11,73",
          },
          {
            VALOR: "6307",
            DESCRICAO: "CREDITOS A VENCER DE 1081 A 1440 DIAS",
            QTD_MESES: "48",
            PERCENTUAL: "9,43",
          },
        ],
        PERCENTUAL: "65,97",
      },
      CREDITO_VENCIDO: {
        VALOR: "20347,00",
        OPERACOES: [
          {
            VALOR: "1319",
            DESCRICAO: "CREDITOS VENCIDOS DE 31 A 60 DIAS",
            QTD_MESES: "2",
            PERCENTUAL: "1,97",
          },
          {
            VALOR: "1346",
            DESCRICAO: "CREDITOS VENCIDOS DE 61 A 90 DIAS",
            QTD_MESES: "3",
            PERCENTUAL: "2,01",
          },
          {
            VALOR: "1372",
            DESCRICAO: "CREDITOS VENCIDOS DE 91 A 120 DIAS",
            QTD_MESES: "4",
            PERCENTUAL: "2,05",
          },
          {
            VALOR: "1413,00",
            DESCRICAO: "CREDITOS VENCIDOS DE 121 A 150 DIAS",
            QTD_MESES: "5",
            PERCENTUAL: "2,11",
          },
          {
            VALOR: "1429",
            DESCRICAO: "CREDITOS VENCIDOS DE 151 A 180 DIAS",
            QTD_MESES: "6",
            PERCENTUAL: "2,14",
          },
          {
            VALOR: "3585,00",
            DESCRICAO: "CREDITOS VENCIDOS DE 181 A 240 DIAS",
            QTD_MESES: "8",
            PERCENTUAL: "5,36",
          },
          {
            VALOR: "8041,00",
            DESCRICAO: "CREDITOS VENCIDOS DE 241 A 300 DIAS",
            QTD_MESES: "10",
            PERCENTUAL: "12,02",
          },
          {
            VALOR: "1842",
            DESCRICAO: "CREDITOS VENCIDOS DE 301 A 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "2,75",
          },
        ],
        PERCENTUAL: "30,41",
      },
    },
    operacoes: [
      {
        TOTAL: "4042,00",
        MODALIDADE: {
          CODIGO: "02",
          DESCRICAO: "EMPRESTIMOS",
        },
        PERCENTUAL: "6,04",
        VENCIMENTOS: [
          {
            VALOR: "894",
            CODIGO: "V120",
            DESCRICAO: "CREDITOS A VENCER DE 31 A 60 DIAS",
            QTD_MESES: "2",
            PERCENTUAL: "1,34",
            RESTRITIVO: "0",
          },
          {
            VALOR: "1154",
            CODIGO: "V140",
            DESCRICAO: "CREDITOS A VENCER DE 91 A 180 DIAS",
            QTD_MESES: "6",
            PERCENTUAL: "1,72",
            RESTRITIVO: "0",
          },
          {
            VALOR: "1759",
            CODIGO: "V150",
            DESCRICAO: "CREDITOS A VENCER DE 181 A 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "2,63",
            RESTRITIVO: "0",
          },
          {
            VALOR: "235",
            CODIGO: "V160",
            DESCRICAO: "CREDITOS A VENCER DE 361 A 720 DIAS",
            QTD_MESES: "24",
            PERCENTUAL: "0,35",
            RESTRITIVO: "0",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "02",
          DESCRICAO: "CREDITO PESSOAL - COM CONSIGNACAO EM FOLHA DE PAGAMENTO.",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "99,00",
        MODALIDADE: {
          CODIGO: "02",
          DESCRICAO: "EMPRESTIMOS",
        },
        PERCENTUAL: "0,15",
        VENCIMENTOS: [
          {
            VALOR: "99",
            CODIGO: "V110",
            DESCRICAO: "CREDITOS A VENCER ATE 30 DIAS",
            QTD_MESES: "1",
            PERCENTUAL: "0,15",
            RESTRITIVO: "0",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "04",
          DESCRICAO: "CREDITO ROTATIVO VINCULADO A CARTAO DE CREDITO",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "284,00",
        MODALIDADE: {
          CODIGO: "02",
          DESCRICAO: "EMPRESTIMOS",
        },
        PERCENTUAL: "0,42",
        VENCIMENTOS: [
          {
            VALOR: "284",
            CODIGO: "V255",
            DESCRICAO: "CREDITOS VENCIDOS DE 181 A 240 DIAS",
            QTD_MESES: "8",
            PERCENTUAL: "0,42",
            RESTRITIVO: "1",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "10",
          DESCRICAO: "CARTAO DE CREDITO – COMPRA, FATURA PARCELADA OU SAQUE FINANCIADO PELA INSTITUICAO EMITENTE DO CARTAO",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "13,00",
        MODALIDADE: {
          CODIGO: "02",
          DESCRICAO: "EMPRESTIMOS",
        },
        PERCENTUAL: "0,02",
        VENCIMENTOS: [
          {
            VALOR: "13",
            CODIGO: "V245",
            DESCRICAO: "CREDITOS VENCIDOS DE 121 A 150 DIAS",
            QTD_MESES: "5",
            PERCENTUAL: "0,02",
            RESTRITIVO: "1",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "13",
          DESCRICAO: "CHEQUE ESPECIAL",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "5056,00",
        MODALIDADE: {
          CODIGO: "02",
          DESCRICAO: "EMPRESTIMOS",
        },
        PERCENTUAL: "7,56",
        VENCIMENTOS: [
          {
            VALOR: "354",
            CODIGO: "V255",
            DESCRICAO: "CREDITOS VENCIDOS DE 181 A 240 DIAS",
            QTD_MESES: "8",
            PERCENTUAL: "0,53",
            RESTRITIVO: "1",
          },
          {
            VALOR: "4702",
            CODIGO: "V260",
            DESCRICAO: "CREDITOS VENCIDOS DE 241 A 300 DIAS",
            QTD_MESES: "10",
            PERCENTUAL: "7,03",
            RESTRITIVO: "1",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "18",
          DESCRICAO: "CARTAO DE CREDITO - NAO MIGRADO 50 RECEBIVEIS ADQUIRIDOS",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "54882,00",
        MODALIDADE: {
          CODIGO: "04",
          DESCRICAO: "FINANCIAMENTOS",
        },
        PERCENTUAL: "82,03",
        VENCIMENTOS: [
          {
            VALOR: "2560",
            CODIGO: "V110",
            DESCRICAO: "CREDITOS A VENCER ATE 30 DIAS",
            QTD_MESES: "1",
            PERCENTUAL: "3,83",
            RESTRITIVO: "0",
          },
          {
            VALOR: "1242",
            CODIGO: "V120",
            DESCRICAO: "CREDITOS A VENCER DE 31 A 60 DIAS",
            QTD_MESES: "2",
            PERCENTUAL: "1,86",
            RESTRITIVO: "0",
          },
          {
            VALOR: "1219",
            CODIGO: "V130",
            DESCRICAO: "CREDITOS A VENCER DE 61 A 90 DIAS",
            QTD_MESES: "3",
            PERCENTUAL: "1,82",
            RESTRITIVO: "0",
          },
          {
            VALOR: "3514",
            CODIGO: "V140",
            DESCRICAO: "CREDITOS A VENCER DE 91 A 180 DIAS",
            QTD_MESES: "6",
            PERCENTUAL: "5,25",
            RESTRITIVO: "0",
          },
          {
            VALOR: "6428",
            CODIGO: "V150",
            DESCRICAO: "CREDITOS A VENCER DE 181 A 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "9,61",
            RESTRITIVO: "0",
          },
          {
            VALOR: "10770",
            CODIGO: "V160",
            DESCRICAO: "CREDITOS A VENCER DE 361 A 720 DIAS",
            QTD_MESES: "24",
            PERCENTUAL: "16,10",
            RESTRITIVO: "0",
          },
          {
            VALOR: "7848",
            CODIGO: "V165",
            DESCRICAO: "CREDITOS A VENCER DE 721 A 1080 DIAS",
            QTD_MESES: "36",
            PERCENTUAL: "11,73",
            RESTRITIVO: "0",
          },
          {
            VALOR: "6307",
            CODIGO: "V170",
            DESCRICAO: "CREDITOS A VENCER DE 1081 A 1440 DIAS",
            QTD_MESES: "48",
            PERCENTUAL: "9,43",
            RESTRITIVO: "0",
          },
          {
            VALOR: "1319",
            CODIGO: "V220",
            DESCRICAO: "CREDITOS VENCIDOS DE 31 A 60 DIAS",
            QTD_MESES: "2",
            PERCENTUAL: "1,97",
            RESTRITIVO: "1",
          },
          {
            VALOR: "1346",
            CODIGO: "V230",
            DESCRICAO: "CREDITOS VENCIDOS DE 61 A 90 DIAS",
            QTD_MESES: "3",
            PERCENTUAL: "2,01",
            RESTRITIVO: "1",
          },
          {
            VALOR: "1372",
            CODIGO: "V240",
            DESCRICAO: "CREDITOS VENCIDOS DE 91 A 120 DIAS",
            QTD_MESES: "4",
            PERCENTUAL: "2,05",
            RESTRITIVO: "1",
          },
          {
            VALOR: "1400",
            CODIGO: "V245",
            DESCRICAO: "CREDITOS VENCIDOS DE 121 A 150 DIAS",
            QTD_MESES: "5",
            PERCENTUAL: "2,09",
            RESTRITIVO: "1",
          },
          {
            VALOR: "1429",
            CODIGO: "V250",
            DESCRICAO: "CREDITOS VENCIDOS DE 151 A 180 DIAS",
            QTD_MESES: "6",
            PERCENTUAL: "2,14",
            RESTRITIVO: "1",
          },
          {
            VALOR: "2947",
            CODIGO: "V255",
            DESCRICAO: "CREDITOS VENCIDOS DE 181 A 240 DIAS",
            QTD_MESES: "8",
            PERCENTUAL: "4,40",
            RESTRITIVO: "1",
          },
          {
            VALOR: "3339",
            CODIGO: "V260",
            DESCRICAO: "CREDITOS VENCIDOS DE 241 A 300 DIAS",
            QTD_MESES: "10",
            PERCENTUAL: "4,99",
            RESTRITIVO: "1",
          },
          {
            VALOR: "1842",
            CODIGO: "V270",
            DESCRICAO: "CREDITOS VENCIDOS DE 301 A 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "2,75",
            RESTRITIVO: "1",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "01",
          DESCRICAO: "AQUISICAO DE BENS – VEICULOS AUTOMOTORES",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "110,00",
        MODALIDADE: {
          CODIGO: "13",
          DESCRICAO: "OUTROS CREDITOS",
        },
        PERCENTUAL: "0,16",
        VENCIMENTOS: [
          {
            VALOR: "110",
            CODIGO: "V110",
            DESCRICAO: "CREDITOS A VENCER ATE 30 DIAS",
            QTD_MESES: "1",
            PERCENTUAL: "0,16",
            RESTRITIVO: "0",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "04",
          DESCRICAO: "CARTAO DE CREDITO - COMPRA A VISTA E PARCELADO LOJISTA",
        },
        VARIACAO_CAMBIAL: "0",
      },
      {
        TOTAL: "2420,00",
        MODALIDADE: {
          CODIGO: "19",
          DESCRICAO: "LIMITE",
        },
        PERCENTUAL: "3,62",
        VENCIMENTOS: [
          {
            VALOR: "2420",
            CODIGO: "V40",
            DESCRICAO: "LIMITE DE CREDITO COM VENCIMENTO ACIMA DE 360 DIAS",
            QTD_MESES: "12",
            PERCENTUAL: "3,62",
            RESTRITIVO: "0",
          },
        ],
        SUB_MODALIDADE: {
          CODIGO: "04",
          DESCRICAO: "CARTAO DE CREDITO",
        },
        VARIACAO_CAMBIAL: "0",
      },
    ],
    score: {
      pontuacao: "125",
      faixa: "PESSIMO",
    },
  },
  
  totals: {
    grossTotal: 190828.59,
    uniqueTotal: 98654.57,
  },
};