version: "3.9"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: consultas-pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@123456a_homol"
    ports:
      - "5432:5432"
    volumes:
      - consultas-pro-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - consultas-pro-redis:/data

volumes:
  consultas-pro-postgres:
  consultas-pro-redis:
