import type { ReportTemplate } from "../schema/template";
import { FRAME_PRESETS } from "../utils/frames-presets";
import { newId } from "../utils/ids";

export function createSampleTemplate(): ReportTemplate {
  const frame = FRAME_PRESETS["a4-p"];
  const frameId = newId("frame");
  const fx = 0;
  const fy = 0;
  let z = 1;
  const id = () => newId("el");
  const styleBase = {
    fontFamily: "Inter, sans-serif",
    fontSize: 13,
    color: "#0f172a",
    lineHeight: 1.4,
    textAlign: "left" as const,
    padding: 6,
  };

  return {
    id: newId("tpl"),
    name: "Relatório de Score — Exemplo",
    version: 1,
    canvas: { background: "#e2e8f0", grid: 8 },
    frames: [
      {
        id: frameId,
        name: "Relatório A4",
        preset: "a4-p",
        x: fx,
        y: fy,
        width: frame.width,
        height: frame.height,
      },
    ],
    elements: [
      // Header band
      {
        id: id(),
        type: "card",
        frameId,
        name: "Header",
        x: fx + 32,
        y: fy + 32,
        width: 730,
        height: 80,
        zIndex: z++,
        style: {
          ...styleBase,
          background: "#0f172a",
          color: "#ffffff",
          borderRadius: 8,
          padding: 16,
        },
        data: {
          title: "{{empresa.nome}}",
          body: "Relatório de Crédito · Protocolo {{consulta.protocolo}} · {{consulta.data}}",
        },
      },
      // Dados pessoais
      {
        id: id(),
        type: "text",
        frameId,
        name: "Seção: Dados Pessoais",
        x: fx + 32,
        y: fy + 140,
        width: 730,
        height: 28,
        zIndex: z++,
        style: { ...styleBase, fontSize: 16, fontWeight: 700 },
        data: { text: "Dados Pessoais" },
      },
      {
        id: id(),
        type: "text",
        frameId,
        name: "Nome",
        x: fx + 32,
        y: fy + 172,
        width: 360,
        height: 26,
        zIndex: z++,
        style: styleBase,
        data: { text: "Nome: {{cliente.nome}}" },
      },
      {
        id: id(),
        type: "text",
        frameId,
        name: "CPF",
        x: fx + 400,
        y: fy + 172,
        width: 362,
        height: 26,
        zIndex: z++,
        style: styleBase,
        data: { text: "CPF: {{cliente.cpf}}" },
      },
      // Resumo financeiro - KPIs
      {
        id: id(),
        type: "text",
        frameId,
        name: "Seção: Resumo Financeiro",
        x: fx + 32,
        y: fy + 220,
        width: 730,
        height: 28,
        zIndex: z++,
        style: { ...styleBase, fontSize: 16, fontWeight: 700 },
        data: { text: "Resumo Financeiro" },
      },
      {
        id: id(),
        type: "card",
        frameId,
        name: "KPI Total Dívidas",
        x: fx + 32,
        y: fy + 252,
        width: 235,
        height: 90,
        zIndex: z++,
        style: {
          ...styleBase,
          background: "#ffffff",
          borderColor: "#e2e8f0",
          borderWidth: 1,
          borderRadius: 8,
          padding: 14,
        },
        data: {
          title: "Total apontado",
          body: "R$ {{consulta.totalDividas}}",
        },
      },
      {
        id: id(),
        type: "card",
        frameId,
        name: "KPI Score",
        x: fx + 280,
        y: fy + 252,
        width: 235,
        height: 90,
        zIndex: z++,
        style: {
          ...styleBase,
          background: "#ffffff",
          borderColor: "#e2e8f0",
          borderWidth: 1,
          borderRadius: 8,
          padding: 14,
        },
        data: { title: "Score", body: "{{cliente.score}}" },
      },
      {
        id: id(),
        type: "card",
        frameId,
        name: "KPI Inadimplência",
        x: fx + 528,
        y: fy + 252,
        width: 234,
        height: 90,
        zIndex: z++,
        style: {
          ...styleBase,
          background: "#ffffff",
          borderColor: "#e2e8f0",
          borderWidth: 1,
          borderRadius: 8,
          padding: 14,
        },
        data: { title: "Chance de inadimplência", body: "12%" },
      },
      // Divider
      {
        id: id(),
        type: "divider",
        frameId,
        name: "Divisor",
        x: fx + 32,
        y: fy + 364,
        width: 730,
        height: 2,
        zIndex: z++,
        style: { ...styleBase, background: "#cbd5e1", padding: 0 },
      },
      // Tabela de dívidas
      {
        id: id(),
        type: "text",
        frameId,
        name: "Seção: Tabela de Dívidas",
        x: fx + 32,
        y: fy + 380,
        width: 730,
        height: 28,
        zIndex: z++,
        style: { ...styleBase, fontSize: 16, fontWeight: 700 },
        data: { text: "Dívidas em aberto" },
      },
      {
        id: id(),
        type: "table",
        frameId,
        name: "Tabela de Dívidas",
        x: fx + 32,
        y: fy + 412,
        width: 730,
        height: 220,
        zIndex: z++,
        style: {
          ...styleBase,
          background: "#ffffff",
          borderColor: "#e2e8f0",
          borderWidth: 1,
          borderRadius: 6,
          padding: 0,
          fontSize: 12,
        },
        data: {
          arrayPath: "dividas",
          columns: [
            { label: "Credor", path: "credor" },
            { label: "Valor", path: "valor", format: "currency" },
            { label: "Data", path: "data" },
          ],
        },
      },
    ],
  };
}